---
# Installed root filesystem payload in the live ISO.
#
# Calamares mounts the SquashFS temporarily and copies its contents
# into the target root mount point created by the mount module.
unpack:
  - source: "/usr/share/calamares/rootfs.sqfs"
    sourcefs: "squashfs"
    destination: ""
